spring:
  datasource:
    url: jdbc:mysql://43.154.165.3:3306/CS_75921?serverTimezone=GMT%2B8&useSSL=false&characterEncoding=utf-8
    username: root
    password: rootdd
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    property-naming-strategy: CAMEL_CASE_TO_LOWER_CASE_WITH_UNDERSCORES
    default-property-inclusion: ALWAYS
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB

