server: 
  port: 5000
  servlet: 
    context-path: /api
###服务的名字名称(该服务注册到eureka注册中心的名称)
spring:
  application:
    name: app-project  #在订单系统的application.yml叫app-order
###服务注册到eureka注册中心的地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8100/eureka
    ###因为该应用为服务提供者，是eureka的一个客户端，需要注册到注册中心
    register-with-eureka: true
    ###是否需要从eureka上检索服务
    fetch-registry: true
  instance:
    prefer-ip-address: true #将自己的ip地址注册到Eureka服务中
    ip-address: localhost
    instance-id: ${server.port} #指定实例id
    

feign:
  #替换掉JDK默认HttpURLConnection实现的 Http Client
  httpclient:
    enabled: true
  #开启hystrix断路器
  hystrix:
    enabled: true
  client:
    config:
      # 全局配置
      default:
       #连接超时时间
        connectTimeout: 10000
       #读取超时时间
        readTimeout: 10000
      # 实例配置，feignName即@feignclient中的value，也就是被调用的服务名
      app-customized:
        connectTimeout: 10000
        readTimeout: 10000
        loggerLevel: full
        
ribbon:
  http:
    client:
      enabled: true  
  #同一台实例的最大自动重试次数，默认为1次，不包括首次
  MaxAutoRetries: 1
  #重试切换实例的次数，默认1，不包括第一次被调用的实例
  MaxAutoRetriesNextServer: 1
  #是否所有的操作都重试，默认为false
  OkToRetryOnAllOperations: true
  #从注册中心刷新服务器列表信息的时间间隔，默认为2000毫秒，即2秒
  ServerListRefreshInterval: 10000
  #请求连接的超时时间，单位为毫秒
  ConnectTimeout: 10000
  #请求读取的超时时间，单位为毫秒
  ReadTimeout: 10000 
  #对指定Http响应码进行重试
  retryableStatusCodes: 404,500,502
      
logging:
  level:
    com.project.demo.rpc.feignClient.CustomizedGoodsRPCFeignClient: DEBUG # 将Feign接口的日志级别设置成DEBUG，因为Feign的Logger.Level只对DEBUG作出响应。